version: '3.8'

services:
  directstreambuffer:
    build:
      context: .
      dockerfile: Dockerfile
    image: directstreambuffer:latest
    container_name: directstreambuffer
    
    # Required for raw socket operations
    privileged: true
    
    # Alternative to privileged mode (more secure)
    # cap_add:
    #   - NET_RAW
    #   - NET_ADMIN
    
    # Use host networking to access physical interfaces
    network_mode: host
    
    # Keep container running for interactive use
    stdin_open: true
    tty: true
    
    # Override default command for interactive shell
    command: /bin/bash
    
    # Mount source code for development (optional)
    volumes:
      - .:/workspace
    
    working_dir: /app
    
    # Environment variables
    environment:
      - TERM=xterm-256color
